name: network_medicine_tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.12
  - conda-forge::jupyterlab=4.3
  - conda-forge::pandas=2.2
  - conda-forge::networkx=3.5
  - conda-forge::matplotlib=3.10.5
  - conda-forge::scipy=1.16.0
  - bioconda::nedrex=0.1.4
  - bioconda::nextflow=24.10.5
  - bioconda::pcst-fast=1.0.10
