name: network_medicine_tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - jupyterlab=4.3
  - pandas=2.2
  - networkx=3.5
  - matplotlib=3.10.5
  - scipy=1.16.0
  - graph-tool
  - nedrex=0.1.4
  - nextflow=24.10.5
  - pcst-fast=1.0.10
  - gprofiler-official
  - requests
